### ISSUE TITLE
Pactus contribuors

### ISSUE THREAD

**Issue by b00f** [b00f/pactus#3]
@RiXelanya @drgpxx @qmajid @mcmxcdev @jemiluv8

Hi,

I hope you are doing well.

It's been a while since we last heard from you regarding the Pactus project. 
We are excited to announce that we have launched it! 
As one of our early contributors, we have some good news for you.
We have allocated tokens for early contributors, including you. 
To proceed, we need your email address. 
If you don't mind, please share your email address with us here in this issue.

Thanks!

**Comment by qmajid** [comment]
Hello. Thanks very well for your suggestion.
***@***.***

**Comment by b00f** [comment]
@qmajid email is masked, please email info@pactus.org

**Comment by qmajid** [comment]
Excuse me, what is reason to send email to ***@***.***?

**Comment by jemiluv8** [comment]
@b00f, for starters, it didn't seem "safe" to be sharing our emails here.
Anyone can come across this issue and see a bunch of emails they can troll.

@qmajid, what @b00f is suggesting is that you send your email to the info**
email specified above instead of writing it here since github is masking the emails here

**Comment by b00f** [comment]
@RiXelanya @drgpxx @qmajid @mcmxcdev @jemiluv8

Please email it by end of today. This issue will be deleted then
